import { createSlice } from "@reduxjs/toolkit"; // Import createSlice function from Redux Toolkit

// Initial state retrieved from localStorage if available, otherwise defaults to an empty array
const initialState = localStorage.getItem("information")
  ? JSON.parse(localStorage.getItem("information"))
  : [];

const informationSlice = createSlice({
  name: "information", // Name of the slice, used in Redux DevTools and actions
  initialState: initialState, // Initial state as defined above
  reducers: {
    // Reducer function to handle adding/updating key skills information
    addinformation(state, action) {
      const newinformation = action.payload; // Extract payload (new key skills information) from action
      localStorage.setItem("information", JSON.stringify(newinformation)); // Update localStorage with new key skills info
      return newinformation; // Return the new key skills info as the updated state
    },
    
    
  },
});
// Export actions generated by createSlice for external use
export const { addinformation } = informationSlice.actions;


// Export the reducer function generated by createSlice
export default informationSlice.reducer;
